apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheusserviceaccount
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.34.0
          imagePullPolicy: IfNotPresent
          args:
            - '--storage.tsdb.retention=6h'
            - '--storage.tsdb.path=/prometheus/'
            - '--config.file=/etc/prometheus/prometheus.yml'
          ports:
            - name: web
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: alert-config-volume
              mountPath: /etc/prometheus/conf
            - name: prometheus-volume
              mountPath: /prometheus
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
        fsGroup: 65534
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: alert-config-volume
          configMap:
            name: prometheus-alertrules-configmap
  volumeClaimTemplates:
    - metadata:
        name: prometheus-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"