# Source: prometheus-msteams/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-msteams
  labels:
    app: prometheus-msteams
    chart: prometheus-msteams-1.3.0
    release: release-name
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-msteams
      release: release-name
  template:
    metadata:
      labels:
        app: prometheus-msteams
        release: release-name
      annotations:
        checksum/config: 473d95770770183ed28183046400ddacb6af9e7b07b4ea65fdcac18c17279587
        checksum/msteams-card-templates: 159dd39e0712672ba37bc14f6e24aa99dba9f049a10e13c8f42de11788e74a96
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-msteams-config
        - name: card-template-volume
          configMap:
            name: prometheus-msteams-card-template
      containers:
        - name: prometheus-msteams
          image: "quay.io/prometheusmsteams/prometheus-msteams:v1.5.0"
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: card-template-volume
              mountPath: /etc/template
          args:
            - -config-file=/etc/config/connectors.yaml
            - -template-file=/etc/template/card.tmpl
          ports:
          - name: http
            containerPort: 2000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 1m
              memory: 8Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000