# Source: prometheus-msteams/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-msteams
  labels:
    app: prometheus-msteams
    chart: prometheus-msteams-1.3.0
    release: release-name
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: http
      protocol: TCP
  selector:
    app: prometheus-msteams
    release: release-name
